version: '3.8'
services:
  flask-backend:
    image: aungkowin/my-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - mongo
  nginx-frontend:
    image: aungkowin/my-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - flask-backend
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"